name: 🤖 Python Quality

run-name: 🤖 Python Quality (Triggered by ${{ github.actor }})

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  quality:
    uses: albr21/gha-reusable-workflows/.github/workflows/reusable-python-quality.yml@main
    secrets: inherit